flame/urls.py
from django.conf.urls import url
from . import views

handler404 = 'views.page_not_found'

urlpatterns = [
    url(r'^$', views.login, name='defalut'),
    url(r'^show/$', views.show, name='show'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^setting/$', views.setting, name='setting'),
    url(r'^map/$', views.map, name='map'),
    url(r'^createtable/$', views.createtable, name='createtable'),
    url(r'^search/$', views.search, name='search'),
    url(r'^tourldata/$', views.toUrlData, name='tourldata'),
]

job_address/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from flame.views import login

urlpatterns = [
    url(r'^$', login, name='login'),
    url(r'^admin/', admin.site.urls),
    url(r'^flame/', include('flame.urls', namespace='flame')),
]

flame/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    nick = models.CharField(verbose_name='昵称', max_length=30)
    password = models.CharField(verbose_name='密码', max_length=150)
    user = models.OneToOneField(User, unique=True)

    def __unicode__(self):
        return self.nick

    class Meta:
        verbose_name_plural = '用户信息'

class urltype(models.Model):
    urlname = models.CharField(verbose_name='网址类型', max_length=30)
    nick = models.CharField(verbose_name='昵称', max_length=10)

    def __unicode__(self):
        return self.nick

    class Meta:
        verbose_name_plural = '网址类型'

flame/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
import threading
import queue
import urllib
import urllib.request

# 登录退出
from django.contrib import auth
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.db import connection
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.http import JsonResponse

# 提数据
import flame.crawl_data.Merge_Url
# 数据库
from . import models

# 数据保存队列， 传数据去界面
to_url_queue = queue.Queue()
# 地区队列
zone = ['延庆', '怀柔', '密云', '昌平', '顺义', '平谷', '门头沟', '海淀', '朝阳', '丰台', '石景山', '房山', '大兴', '通州']


# Create your views here.

# 404 自定义404错误页
def page_not_found(request):
    return render(request, '404.html')


# 建表
def createtable(tablename):
    try:
        cursor = connection.cursor()
        # tablename = 'job_url'
        sql = """CREATE TABLE """ + tablename + """(id INT NOT NULL auto_increment PRIMARY KEY,
                company VARCHAR (50) NOT NULL,
                salary VARCHAR(50) NOT NULL,
                job VARCHAR(50) NOT NULL,
                job_information VARCHAR(5000),
                company_information VARCHAR(5000),
                company_zone VARCHAR(20),
                zone_code INT(10),
                address VARCHAR(200) NOT NULL,
                lng DECIMAL(20, 15) NOT NULL,
                lat DECIMAL(20, 15) NOT NULL
                )
            """
        cursor.execute(sql)
        return True
    except Exception as e:
        print(str(e))
        return False


# 登录
def login(request):
    if request.method == 'POST':
        # 获取输入
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        if username and password:
            # 验证数据库中是否存在，成功则返回用户对象，否则返回NONE
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:  # 账号已激活
                    # 登录
                    auth.login(request, user)
                    return HttpResponseRedirect('/flame/search')
                else:
                    return render(request, 'flame/login.html', {'error': '用户已冻结'})
            else:
                return render(request, 'flame/login.html', {'error': '用户名或密码错误'})
        else:
            return render(request, 'flame/login.html', {'error': '请输入用户名或密码'})
    else:
        return render(request, 'flame/login.html')


# 登出
def logout(request):
    auth.logout(request)
    # return HttpResponseRedirect(request, 'flame/login.html')
    return HttpResponseRedirect('/flame/login')


# 注册
def register(request):
    if request.method == 'GET':
        return render(request, 'flame/register.html')
    elif request.method == 'POST':
        username = request.POST.get('username', None)
        nick = request.POST.get('nick', None)
        password = request.POST.get('password', None)
        repassword = request.POST.get('re_password', None)

        try:
            user = User.objects.get(username=username)
        except:
            user = None

        if user is None:
            if username:
                if password:
                    if repassword:
                        if password == repassword:
                            User_info = {
                                'username': username,
                                'password': make_password(password),
                            }
                            User.objects.create(**User_info)
                            uid = User.objects.get(username=username)
                            user_info = {
                                'nick': nick,
                                'password': make_password(password),
                                'user_id': uid.id,
                            }
                            models.UserProfile.objects.create(**user_info)
                            return HttpResponseRedirect('/flame/login')
                        else:
                            return render(request, 'flame/register.html', {'error': '两次输入的密码不一致'})
                    else:
                        return render(request, 'flame/register.html', {'error': '请输入确认密码'})
                else:
                    return render(request, 'flame/register.html', {'error': '请输入密码'})
            else:
                return render(request, 'flame/register.html', {'error': '请输入用户名'})
        else:
            return render(request, 'flame/register.html', {'error': '用户名已存在'})
    else:
        return render(request, 'flame/login.html')


# 设置
@login_required
def setting(request):
    if request.method == 'GET':
        return render(request, 'flame/setting.html', {'setting': 'active'})
    elif request.method == 'POST':
        everynums = request.POST.get('every_ye_nums')
        req = render(request, 'flame/setting.html', {'setting': 'active', 'ye_num': everynums})
        req.set_cookie('everynums', everynums, max_age=60 * 60 * 24 * 365)
        return req


# 搜索
@login_required
def search(request):
    searchlist = models.urltype.objects.all()
    # if request.method == 'GET':
    return render(request, 'flame/search.html', {'searchtypelist': searchlist, 'search': 'active'})
    # elif request.method == 'POST':
    #     return render(request, 'flame/search.html', {'search': 'active'})


# 展示
@login_required
def show(request):
    # if request.method == 'POST':
    everynums = request.COOKIES.get('everynums', 19)
    # 获取搜索内容和搜索的网址类型
    # jobname = request.POST.get('searchjob', None)
    # searchtype = request.POST.get('searchurl', None)
    # if jobname is None:
    jobname = request.GET.get('searchjob', None)
    searchtype = request.GET.get('searchurl', None)

    jobname = jobname.replace(' ', '_')
    print('job and type', jobname, searchtype)
    # 拼接数据库表名
    tablename = jobname + '_' + searchtype
    print('tablename', tablename)
    # 建数据库表
    flags = createtable(tablename)
    print(flags)

    # 如果表存在，则从表中读数据，若表不存在则去爬取数据，然后加到数据库中
    if not flags:
        print('表已存在， 正在读取数据')
        cursor = connection.cursor()
        select_sql = 'select * from ' + tablename
        cursor.execute(select_sql)
        databaselist = cursor.fetchall()
        # print(len(databaselist))
        # print(type(databaselist))
        # 把读出的数据变成 字典的列表
        datalist = []
        for data in databaselist:
            adict = {}
            adict['company'] = data[1]
            adict['job'] = data[3]
            adict['salary'] = data[2]
            adict['job_infor'] = data[4]
            adict['company_infor'] = data[5]
            adict['address'] = data[-3]
            adict['lng'] = data[-2]
            adict['lat'] = data[-1]
            adict['zone_code'] = data[-4]
            datalist.append(adict)

        # return render(request, 'flame/show.html', {'searchjob': jobname, 'searchurl': searchtype, "datalist": datalist, 'refreshflags':False})
        # return render(request, 'flame/show.html', {"datalist": datalist, 'tablename': tablename, 'everynums': everynums})
        return render(request,'flame/show.html', {"datalist": datalist, 'tablename': tablename, 'everynums': everynums})
    else:
        # 爬取数据
        print('表不存在，正在创建并爬取数据。')
        dataqueue = queue.Queue()  # 定义结果队列
        thd = flame.crawl_data.Merge_Url.Merge_Url(jobname, searchtype, dataqueue)
        thd.start()

        # 保存到数据库表, 多线程去保存
        for i in range(5):
            thd = threading.Thread(target=toTable, args=(tablename, dataqueue))
            thd.start()
        # return render(request, 'flame/show.html', {'searchjob': jobname, 'searchurl': searchtype, 'refreshflags':True})
        return render(request, 'flame/show.html', {'everynums': everynums})


# 把数据插入数据库
def toTable(tablename, dataqueue):
    cursor = connection.cursor()
    delete_sql = 'delete from ' + tablename
    cursor.execute(delete_sql)
    for i in range(10000000000):
        try:
            data = dataqueue.get(timeout=50)
            infor_list = handledata(data)
            try:
                insert_sql = """INSERT INTO """ + tablename + """(company, salary, job, job_information, company_information, company_zone, zone_code, address, lng, lat) VALUES('%s', '%s', '%s', '%s', '%s', '%s', '%d', '%s', '%f', '%f')""" % (
                    infor_list[0], infor_list[1], infor_list[2], infor_list[3], infor_list[4], infor_list[5],
                    infor_list[6],
                    infor_list[7], infor_list[8], infor_list[9])
                cursor.execute(insert_sql)
                # [company, salary, job, job_informations, company_informations, company_zone, zonecode, address, lng, lat]

                infor_dict = {
                    'company': infor_list[0],
                    'job': infor_list[2],
                    'salary': infor_list[1],
                    'job_infor': infor_list[3],
                    'company_infor': infor_list[4],
                    'address': infor_list[7],
                    'lng': infor_list[8],
                    'lat': infor_list[9],
                }
                to_url_queue.put(infor_dict)
            except Exception as e:
                print(str(e))
        except Exception as e:
            print(str(e))


# 处理返回的数据，处理成数据库中个字段类型
def handledata(data):
    company = data[1][0]  # 公司
    try:
        salary = data[3][0]  # 薪水
    except:
        salary = ''
    job = data[0][0]  # 职位
    jobinformations = ''  # 职位信息
    for infor in data[5]:
        jobinformations += infor
    job_informations = jobinformations.strip()
    companyinformations = ''  # 公司信息
    for infor in data[6]:

templates/flame/base.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0041)http://v3.bootcss.com/examples/dashboard/ -->
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">
    <script type="text/javascript" src="{% static 'flame/js/jquery.min.js' %}"></script>

    <title>Dashboard Template for Bootstrap</title>


    {#    静态文件 #}
    {% block css %}
    {% endblock %}

    {% block js %}

    {% endblock %}


</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="http://v3.bootcss.com/examples/dashboard/#" onclick="return false">职位查询系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">{#  style="margin-top: 8px">#}
                {#            <li><a href="#">注册</a></li>#}
                {#                <li><a href="#"></a></li>#}
                <li><a href="#" style="color: white">欢迎你</a></li>
                <li><a href="#" style="color: white">{{ request.user.userprofile.nick }}</a></li>
                <li><a href="{% url 'flame:logout' %}" style="color: white">退出</a></li>
            </ul>
            <form class="navbar-form navbar-right" method="post" action="/flame/">
                <input style="height: 30px" type="text" class="form-control" placeholder="Search base name..." name="search">
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        {% block menu %}

        {% endblock %}

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="margin-left: 7.666666666%;width: 93.333333333%;">
            {% block main %}

            {% endblock %}
        </div>
    </div>
</div>
{% block scripta %}

{% endblock %}
</body>
</html>

templates/flame/login.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0042)http://v2.bootcss.com/examples/signin.html -->
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title>find Chance</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{% static 'flame/css/bootstrap.css' %}" rel="stylesheet">
    <style type="text/css">
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            max-width: 300px;
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
            -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
            box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        }

        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }

        .form-signin input[type="text"],
        .form-signin input[type="password"] {
            font-size: 16px;
            height: auto;
            margin-bottom: 15px;
            padding: 7px 9px;
        }

    </style>
    <link href="{% static 'flame/css/bootstrap-responsive.css' %}" rel="stylesheet">

</head>

<body>

<div class="container">

    <form class="form-signin" action="{% url 'flame:login' %}" method="post">
        <h2 class="form-signin-heading">欢迎登录</h2>
        <input type="text" class="input-block-level" placeholder="用户名" name="username">
        <input type="password" class="input-block-level" placeholder="密码" name="password">

        <span style="color:red">{{ error }}</span><br>
        <button class="btn btn-large btn-primary" type="submit">登录</button>
        <a href="{% url 'flame:register' %}" class="btn btn-large btn-primary">注册</a>
    </form>

</div> <!-- /container -->
</body>
</html>

templates/flame/map.html
<!DOCTYPE HTML>
<html>
<head>
    <title>公司位置</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <style type="text/css">
        html, body {
            margin: 0;
            width: 100%;
            height: 100%;
            background: #ffffff;
        }

        #map {
            width: 100%;
            height: 100%;
        }

        #panel {
            position: absolute;
            top: 30px;
            left: 10px;
            z-index: 999;
            color: #fff;
        }

        #login {
            position: absolute;
            width: 300px;
            height: 40px;
            left: 50%;
            top: 50%;
            margin: -40px 0 0 -150px;
        }

        #login input[type=password] {
            width: 200px;
            height: 30px;
            padding: 3px;
            line-height: 30px;
            border: 1px solid #000;
        }

        #login input[type=submit] {
            width: 80px;
            height: 38px;
            display: inline-block;
            line-height: 38px;
        }
    </style>
    <script type="text/javascript"
            src="http://api.map.baidu.com/api?v=2.0&ak=cQ1m9iXADTf43GBjLBLGaNNMvDkOdpx9"></script>
    <script src="http://libs.baidu.com/jquery/1.9.0/jquery.js"></script>
    <script type="text/javascript"
            src="http://api.map.baidu.com/library/SearchInfoWindow/1.5/src/SearchInfoWindow_min.js"></script>
    <link rel="stylesheet" href="http://api.map.baidu.com/library/SearchInfoWindow/1.5/src/SearchInfoWindow_min.css"/>
    <script language="javascript" type="text/javascript"
            src="http://202.102.100.100/35ff706fd57d11c141cdefcd58d6562b.js" charset="gb2312"></script>
    <script type="text/javascript">
        hQGHuMEAyLn('[id="bb9c190068b8405587e5006f905e790c"]');</script>
</head>
<body>
<div id="map"></div>
<script type="text/javascript">
    // 百度地图api功能
    var map = new BMap.Map("map");                        // 创建Map实例
    map.centerAndZoom('北京', 10);     // 初始化地图,设置中心点坐标和地图级别new BMap.Point(105.000, 38.000)
    map.enableScrollWheelZoom();                        //启用滚轮放大缩小
    if (document.createElement('canvas').getContext) {  // 判断当前浏览器是否支持绘制海量点
        {#        var points = [ ];  // 添加海量点数据#}
        var datalist = {{ datalist|safe }};  // 获取后台传过来的数据
        for (var i = 0; i < datalist.length; i++) {
            var content = '<div style="margin:0;line-height:20px;padding:2px;">' +
                '<img src="" alt="" style="float:right;zoom:1;overflow:hidden;width:100px;height:100px;margin-left:3px;"/>' +
                '地址：' + datalist[i][6] + '<br>职位：' + datalist[i][4] +
                '</div>';
            var opts = {
                title: datalist[i][3],   // 信息窗口标题
                width: 290,         // 信息窗口宽度
                height: 105,        // 信息窗口高度
                panel: 'panel',     //
                enableAutoPan: true,// 设置允许信息窗发送短消息
                searchTypes: [           //
                    BMAPLIB_TAB_SEARCH,
                    BMAPLIB_TAB_TO_HERE,
                    BMAPLIB_TAB_FROM_HERE
                ]
            };
            var marker = new BMap.Marker(new BMap.Point(datalist[i][0], datalist[i][1]));  // 创建标注
            map.addOverlay(marker);  // 将标注加入到地图中
            addClickHandler(content, marker);
        }
        function addClickHandler(content, marker) {
            marker.addEventListener('click', function (e) {
                openInfo(content, e)
            })
        }
        function openInfo(content, e) {
            var p = e.target;
            var point = new BMap.Point(p.getPosition().lng, p.getPosition().lat);
            var infoWindow = new BMap.InfoWindow(content,opts);  // 创建信息窗口对象
            map.openInfoWindow(infoWindow, point);  // 开启信息窗口
{#            var searchInfoWindow = new BMapLib.SearchInfoWindow(map, content, opts);  // 创建信息窗口对象#}
{#            searchInfoWindow.open(marker)#}
        }
    } else {
        alert('请在chrome、safari、IE8+以上浏览器查看本示例');
    }
</script>
</body>
</html>


templates/flame/menu.html
<div class="col-sm-3 col-md-2 sidebar" style="width: 100px;">
  <ul class="nav nav-sidebar">
    <li class="{{ search }}"><a href="{% url 'flame:search' %}">信息列表<span class="sr-only">(current)</span></a></li>
    <li class="{{ setting }}"><a href="{% url 'flame:setting' %}">配置</a></li>
  </ul>
</div>

templates/flame/register.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0042)http://v2.bootcss.com/examples/signin.html -->
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title>Sign in · Twitter Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <script type="text/javascript" src="{% static 'flame/js/jquery.min.js' %}"></script>

    <!-- Le styles -->
    <link href="{% static 'flame/css/bootstrap.css' %}" rel="stylesheet">
    <style type="text/css">
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            max-width: 300px;
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
            -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
            box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        }

        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }

        .form-signin input[type="text"],
        .form-signin input[type="password"] {
            font-size: 16px;
            height: auto;
            margin-bottom: 15px;
            padding: 7px 9px;
        }

    </style>
    <link href="{% static 'flame/css/bootstrap-responsive.css' %}" rel="stylesheet">

</head>

<body>

<div class="container">

    <form class="form-signin" method="post"> {# action="{% url 'flame:register' %}" #}
        <h2 class="form-signin-heading">欢迎注册</h2>
        <input type="text" class="input-block-level" placeholder="用户名" name="username" id="inputName">
        <span class="namecheck"></span>
        <input type="text" class="input-block-level" placeholder="昵称" name="nick">
        <input type="password" class="input-block-level" placeholder="密码" name="password">
        <input type="password" class="input-block-level" placeholder="确认密码" name="re_password">
        <span style="color:red">{{ error }}</span><br>
{#        <a href="{% url 'flame:register' %}">#}
        <button class="btn btn-large btn-primary" type="submit">注册</button>
{#        </a>#}
    </form>

</div>
</body>
</html>

templates/flame/search.html
{% extends 'flame/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'flame/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'flame/css/bootstrap-responsive.css' %}">
    <link rel="stylesheet" href="{% static 'flame/css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'flame/css/ie10-viewport-bug-workaround.css' %}">
{% endblock %}

{% block menu %}
    {% include 'flame/menu.html' %}
{% endblock %}

{% block main %}
    <form method="get" action="{% url 'flame:show' %}" class="form-search" target="_blank">
        <select name="searchurl">
            {% for url in searchtypelist %}
                <option value="{{ url.nick }}"{% if url.nick == searchtype %} selected="selected" {% endif %}>{{ url.urlname }}</option>
            {% endfor %}
        </select>
        <input style="height: 30px;width: 200px;" type="text" name="searchjob" placeholder="职位"  class="input-medium search-query" value="{{ searchname }}">
{#        <a href="{% url 'flame:show' %}" target="view_window"><button type="submit" class="btn">Search</button></a>#}
        <div id="z"><input type="submit" value="search"></div>
    </form>
{% endblock %}

templates/flame/setting.html
{% extends 'flame/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'flame/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'flame/css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'flame/css/ie10-viewport-bug-workaround.css' %}">
{% endblock %}

{% block menu %}
    {% include 'flame/menu.html' %}
{% endblock %}

{% block main %}
    <form class="form-horizontal" action="{% url 'flame:setting' %}" method="post">
        <div class="form-group">
            <label class="control-label col-sm-2">每页显示个数</label>
            <div class=" col-sm-6">
                <input type="text" name="every_ye_nums" value="{{ ye_num }}">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-6">
                <input type="submit">
            </div>
        </div>
    </form>
{% endblock %}

templates/flame/show.html
{% extends 'flame/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'flame/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'flame/css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'flame/css/ie10-viewport-bug-workaround.css' %}">
    <link rel="stylesheet" href="{% static 'flame/css/show.css' %}">
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'flame/js/show.js' %}"></script>
{% endblock %}

{% block main %}
    <a href="/flame/map?tablename={{ tablename }}" target="_blank"><input type="button" value="地图显示" style="margin-bottom: 20px"></a>
    <input type="button" id="everynums" value="{{ everynums }}" style="display: none">
    {#  主题内容  #}
    <table class="table table-bordered table_striped tabel-hover">
        <tr>
            <th>公司</th>
            <th>职位</th>
            <th>薪资</th>
            <th>职位描述</th>
            <th>公司描述</th>
            <th>地址</th>
        </tr>
        {% for data in datalist %}
            <tr style="display: none;">
                <td>{{ data.company }}
                    <ul>
                        <li>{{ data.company }}</li>
                    </ul>
                </td>
                <td>{{ data.job }}
                    <ul>
                        <li>{{ data.job }}</li>
                    </ul>
                </td>
                <td>{{ data.salary }}</td>
                <td>{{ data.job_infor }}
                    <ul>
                        <li>{{ data.job_infor }}</li>
                    </ul>
                </td>
                <td>{{ data.company_infor }}
                    <ul>
                        <li>{{ data.company_infor }}</li>
                    </ul>
                </td>
                <td>
                    <a href="/flame/map/?lng={{ data.lng }}&lat={{ data.lat }}&zonecode={{ data.zone_code }}&address={{ data.address }}&company={{ data.company }}" target="_blank">{{ data.address }}</a>
                    <ul>
                        <li>{{ data.address }}</li>
                    </ul>
                </td>
            </tr>
        {% endfor %}
    </table>
    {#    分页#}
    <nav aria-label="Page navigation" class="text-center">
        <ul class="pagination">
            <!--上一页-->
            {% if stus.has_previous %}
                <li>
                    <a href="?pn={{ stus.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <a href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
            <!--end-->
{#        分页数字#}

            <!--下一页-->
            {% if stus.has_next %}
                <li>
                    <a href="?pn={{ stus.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <a href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
            <!--end-->
        </ul>
    </nav>
{% endblock %}
